# Generated by Django 3.2.25 on 2024-03-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-09-19'),
            preserve_default=False,
        ),
    ]
